---
- name: Label K8s nodes
  hosts: virtual-load-balancer
  become: true
  become_user: root

    - name: Set label on for Longhorn storage nodes
      command: kubectl label nodes {{ item }} longhorn-node=true
      loop: "{{ groups['agent-host'] }}"
      delegate_to: "{{ inventory_hostname }}"
