---
- name: Label K8s nodes
  hosts: control-plane-1
  become: true
  become_user: root

  tasks:

    - name: Set label app on worker nodes
      command: kubectl label nodes {{ item }} purpose=app
      loop: "{{ groups['aget-app'] }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Set label build on worker nodes
      command: kubectl label nodes {{ item }} purpose=build
      loop: "{{ groups['agent-build'] }}"
      delegate_to: "{{ inventory_hostname }}"
